learning_rate: 1e-3
epochs: 20
batch_size: 64
train_num: 10
test_num: 100
gamma: 0.9
n_step: 4
target_freq: 60
buffer_size: 20000
eps_train: 0.1
eps_test: 0.05
step_per_epoch: 1000
step_per_collect: 10
hidden_sizes: [32, 32]
num_agents: 2
hetero_prob: 0.
eps_len: 5
logging_dir: 'logs/dqn_baseline_hmg'
