env_name: "CollusionDilemmaLargeEnv"
num_agents: 16
hetero_prob: 0.
eps_len: 16
framework: "torch" # framework specifier, choices=["tf", "tf2", "torch"]
as_test: True # actions: "store_true" or "store_false", script running as test or not
# stop_reward must be achieved within stop_timesteps AND stop_iters
stop_iters: 20 # number of iterations to train
stop_timesteps: 20 # number of timesteps to train
stop_reward: 20 # non-achievable reward goal selection
policy_choices: ["always_same", "beat_last"]
train_batch_size: 1
gamma: 0.5
metric_smoothing_eps_len: 100
gov_rek: True
zero_mean: True
