env_name: "CollusionDilemmaLargeEnv"
num_agents: 16 # for 20 to 25 agent out of memory error produced for my device
hetero_prob: 0.5
eps_len: 16
framework: "torch" # framework specifier, choices=["tf", "tf2", "torch"]
as_test: True # actions: "store_true" or "store_false", script running as test or not
# stop_reward must be achieved within stop_timesteps AND stop_iters
stop_iters: 40 # number of iterations to train
stop_timesteps: 40 # number of timesteps to train
stop_reward: 40 # non-achievable reward goal selection
policy_choices: ["always_same", "beat_last"]
train_batch_size: 1
gamma: 0.5
metric_smoothing_eps_len: 100
gov_rek: True
zero_mean: True
sparse: True
