env_name: "CollusionDilemmaLargeEnv"
num_agents: 25 
hetero_prob: 0.
eps_len: 10
framework: "torch" # framework specifier, choices=["tf", "tf2", "torch"]
as_test: True # actions: "store_true" or "store_false", script running as test or not
# stop_reward must be achieved within stop_timesteps AND stop_iters
stop_iters: 50 # number of iterations to train
stop_timesteps: 10000 # number of timesteps to train
stop_reward: 4096 # feasable reward choice 100 but not arbitrary 4096, reward at which we stop training
policy_choices: ["always_same", "beat_last"]
train_batch_size: 256
gamma: 0.85
metric_smoothing_eps_len: 100
gov_rek: False
